title:             📮 Aezlo 🚀
email:             aezloman@athelo.net
description:       To aezloland, to all.
author:            Aezlo
baseurl:           "/"
url:               "http://blog.athelo.net"
permalink: /:year/:month/:title

# Social Profiles
twitter_username:  aezloman
github_username:   aezloX
facebook_username: #
deviantart_username: aezloman

# Build settings
markdown:          kramdown
paginate:          20
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
