title:             📮 Aezlo 🚀
email:             aezloman@athelo.net
description:       To aezloland, to all.
author:            Aezlo
baseurl:           "/clean-blog"
url:               "http://aezlox.github.io"

# Social Profiles
twitter_username:  aezloman
github_username:   aezloX
facebook_username: #

# Build settings
markdown:          kramdown
paginate:          20
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
